"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const prefabs_1 = require("@diez/prefabs");
exports.default = {
    white: prefabs_1.Color.hex('#FFF'),
    black: prefabs_1.Color.hex('#000'),
    // Mobile Team Colors
    // see: https://fiscalnote2.atlassian.net/wiki/spaces/MNBV/pages/1009221679/Mobile+Design+System
    purplePrimary: prefabs_1.Color.hex('#442547'),
    taupeLight: prefabs_1.Color.hex('#AD9C94'),
    taupeMid: prefabs_1.Color.hex('#826F75'),
    taupeDark: prefabs_1.Color.hex('#635257'),
    tealLight: prefabs_1.Color.hex('#E3F6F7'),
    tealMid: prefabs_1.Color.hex('#85C7CB'),
    tealBright: prefabs_1.Color.hex('#38ACB3'),
    tealPrimary: prefabs_1.Color.hex('#008991'),
    tealDark: prefabs_1.Color.hex('#037D85'),
    tanBackground: prefabs_1.Color.hex('#FBFEF3'),
    tanText: prefabs_1.Color.hex('#F3F7E8'),
    tanLight: prefabs_1.Color.hex('#F0F3E9'),
    tanMid: prefabs_1.Color.hex('#DADCD3'),
    tanDark: prefabs_1.Color.hex('#D2D1C5'),
    greyLightNeutral: prefabs_1.Color.hex('#D8D8D8'),
    night: prefabs_1.Color.hex('#131313'),
    redSunset: prefabs_1.Color.hex('#BF2909'),
    redFire: prefabs_1.Color.hex('#E0310B'),
    orangeOptimistic: prefabs_1.Color.hex('#FF6B2B'),
    yellowBright: prefabs_1.Color.hex('#F0C11C'),
    yellowButtercup: prefabs_1.Color.hex('#F6DC7E'),
    partyRepublican: prefabs_1.Color.hex('#BE2B2B'),
    partyIndependent: prefabs_1.Color.hex('#932079'),
    partyOther: prefabs_1.Color.hex('#635257'),
    partyLibertarian: prefabs_1.Color.hex('#865E00'),
    partyDemocrat: prefabs_1.Color.hex('#2270E5'),
    partyGreen: prefabs_1.Color.hex('#006F3A'),
    spectrumFarRight: prefabs_1.Color.hex('#AF0B0B'),
    spectrumRight: prefabs_1.Color.hex('#BC185D'),
    spectrumMiddle: prefabs_1.Color.hex('#7F3A86'),
    spectrumLeft: prefabs_1.Color.hex('#25AEFB'),
    spectrumFarLeft: prefabs_1.Color.hex('#2270E5'),
    infoOrange: prefabs_1.Color.hex('#F36DDD'),
    infoErrorRed: prefabs_1.Color.hex('#E82733'),
    infoGoodGreen: prefabs_1.Color.hex('#00914C'),
    infoYellowGreen: prefabs_1.Color.hex('#ADA94E'),
    activeGreen: prefabs_1.Color.hex('006F3A'),
    // Marketing Team Colors
    // see: https://drive.google.com/file/d/1k5LXQGbVHQVAyGOaktvUkYpL6WTDXkhO/view
    purpleBold: prefabs_1.Color.hex('#442547'),
    redAlert: prefabs_1.Color.hex('#E0310B'),
    tealTech: prefabs_1.Color.hex('#3AC6CD'),
    tealGrassroot: prefabs_1.Color.hex('#087D85'),
    greyPower: prefabs_1.Color.hex('#939598'),
    greyLight: prefabs_1.Color.hex('#F2F2F2'),
};
//# sourceMappingURL=Colors.js.map